[package]
name = "netutils"
version = "0.1.0"
edition = "2024"

[dependencies]
http.workspace = true
tokio-rustls.workspace = true
hyper-util.workspace = true
hyper.workspace = true
tower.workspace = true
thiserror.workspace = true
http-body.workspace = true
zcash_client_backend.workspace = true
webpki-roots.workspace = true
tonic.workspace = true
hyper-rustls.workspace = true
rustls-pemfile.workspace = true
